### ISSUE TITLE
does not work on windows.

### ISSUE THREAD

**Issue by mboveiri** [abhishekq61/tunnel-client#1]
Windows 10 (1903) Build 18362
it's wasn't start.
after type command `staqlab-tunnel 3000`  nothing happens.
is any command available for verbose.?

**Comment by retromaster137** [comment]
Same story on Windows 7 x64 Build 7601. Linux version works fine under Ubuntu, though.

**Comment by abhishekq61** [comment]
> Windows 10 (1903) Build 18362
> it's wasn't start.
> after type command `staqlab-tunnel 3000` nothing happens.
> is any command available for verbose.?

I have updated the executable files for windows.can you try now

**Comment by abhishekq61** [comment]
> Same story on Windows 7 x64 Build 7601. Linux version works fine under Ubuntu, though.

I have updated the executable files for windows.can you try now

> > Windows 10 (1903) Build 18362
> > it's wasn't start.
> > after type command `staqlab-tunnel 3000` nothing happens.
> > is any command available for verbose.?
> 
> I have updated the executable files for windows.can you try now



> Same story on Windows 7 x64 Build 7601. Linux version works fine under Ubuntu, though.

https://github.com/abhishekq61/tunnel-client/issues/1#issuecomment-622947038

**Comment by mboveiri** [comment]
> > Windows 10 (1903) Build 18362
> > it's wasn't start.
> > after type command `staqlab-tunnel 3000` nothing happens.
> > is any command available for verbose.?
> 
> I have updated the executable files for windows.can you try now

seems it's work now.
thank you.

**Comment by abhishekq61** [comment]
Resolved as per
https://github.com/abhishekq61/tunnel-client/issues/1#issuecomment-622949221
