### ISSUE TITLE
Staqlab Tunnel for Raspberry Pi?

### ISSUE THREAD

**Issue by TheOceanBreeze** [abhishekq61/tunnel-client#3]
Hello.

Are there any plans to make this software compatible with Raspberry Pi and other ARM devices?

**Comment by abhishekq61** [comment]
No, as of now, we are not into embedded system development for this servie

**Comment by TheOceanBreeze** [comment]
What about a release of the source code for the tunnel client? I could possibly look into building a Linux ARM version for this software.

**Comment by abhishekq61** [comment]
We already have linux version released for this
https://github.com/abhishekq61/tunnel-client
The repo for client is private and can't be made open-source.
I am not aware of raspberry pi ecosystem. As you have told it would work on
linux, can you tell the architecture needed.
I would check if could have a version ready for that.
