### ISSUE TITLE
Could you show me how to forward a tcp port? 

### ISSUE THREAD

**Issue by ghost** [abhishekq61/tunnel-client#4]
I need to forward a tcp port on two separate computers so I can use it as a p2p messenger. I already have a working tcp packet messenger, but since most of the time this'll be used of different networks I need to have a Nat solution. So I'm thinking of having each person forward that tcp data to a public ip where the other person listens via versa. And yes Ive planning built in encryption.

How would I do such thing?

**Comment by abhishekq61** [comment]
Didn't exactly got what are you trying to implement. But by rough idea
through your explanation, I suspect you should implement a server which is
listening on a port, and in that port you different peers can connect to
You can implement such server easily in any language, take for example
"net" Library in nodejs.

**Comment by ghost** [comment]
Yeah the problem is I don't have the money for a central server. So I was hoping to use this to make the ips public so I don't have to worry about traversing firewalls

**Comment by asinghall** [comment]
I added how to acheive that in my last commit. Also, i am closing this thread as it does not really feature a bug request.
You can contact me on admin@staqlab.com if you need any other help
