### ISSUE TITLE
staqtunnel page

### ISSUE THREAD

**Issue by xxxdebug** [abhishekq61/tunnel-client#5]
Hi,

We're using staqtunnel now, it works great. However a page is shown when we tunnel into our own page. Something like: "ATTENTION - ignore if you're a developer". Can we remove this page from our process? 

Thanks

**Comment by abhishekq61** [comment]
Hi xxmoC, that page is to avoid phishing through the service. 
You can remove this page by purchasing a pro plan $1/month only.
More details at https://tunnel.staqlab.com/admin/billing/
You will need to sign In to the portal to view billing page

**Comment by xxxdebug** [comment]
Hi,

I just logged in, created an account and try to pay. However it shows: 

As per Indian regulations, only registered Indian businesses (i.e. sole proprietorships, limited liability partnerships and companies, but not individuals) can accept international payments. More info here: https://stripe.com/docs/india-exports

So I cannot pay, I'm NL based (EU)

**Comment by abhishekq61** [comment]
Can you connect with me on email : admin@staqlab.com

**Comment by xxxdebug** [comment]
All fixed. Thanks so much for the good service!
